# Generated by Django 3.2.6 on 2021-11-24 19:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dishes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Блюдо',
                'verbose_name_plural': 'Блюда',
            },
        ),
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=50, verbose_name='Должность')),
                ('responsibilities', models.TextField(max_length=1000, verbose_name='Обязанности')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
            },
        ),
        migrations.CreateModel(
            name='RegularCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=50, verbose_name='Отчетство')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('discount_amount', models.IntegerField(verbose_name='Размер скидки')),
                ('client_status', models.CharField(blank=True, choices=[('Бронзовый', 'Бронзовый'), ('Серебрянный', 'Серебрянный'), ('Золотой', 'Золотой'), ('Платиновый', 'Платиновый')], max_length=50, verbose_name='Статус клиента')),
            ],
            options={
                'verbose_name': 'Постоянный клиент',
                'verbose_name_plural': 'Постоянные клиенты',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=50, verbose_name='Отчетство')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('ingredients', models.CharField(max_length=200, verbose_name='Ингредиенты')),
                ('batch', models.IntegerField(verbose_name='Партия')),
            ],
            options={
                'verbose_name': 'Заготовка',
                'verbose_name_plural': 'Заготовки',
            },
        ),
        migrations.CreateModel(
            name='Workpieces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('ingredients', models.CharField(max_length=200, verbose_name='Ингредиенты')),
                ('date_of_creation', models.DateTimeField(verbose_name='Дата создания')),
                ('expiration_date', models.DateTimeField(verbose_name='Дата истечения срока годности')),
            ],
            options={
                'verbose_name': 'Заготовка',
                'verbose_name_plural': 'Заготовки',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=50, verbose_name='Отчетство')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('work_experience', models.CharField(max_length=20, verbose_name='Опыт работы')),
                ('salary', models.IntegerField(verbose_name='Зарплата')),
                ('position', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.positions', verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('Создан', 'Создан'), ('Отменен', 'Отменен'), ('Отдан на кухню', 'Отдан на кухню'), ('Готовится', 'Готовится'), ('На подаче', 'На подаче'), ('Ожидает оплаты', 'Ожидает оплаты'), ('Оплачен', 'Оплачен')], default='Создан', max_length=50, verbose_name='Статус заказа')),
                ('cost_of_the_order', models.IntegerField(verbose_name='Стоимость заказа')),
                ('composition', models.ManyToManyField(related_name='orders', to='main_app.Dishes', verbose_name='Состав заказа')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='main_app.regularcustomer', verbose_name='Карта постоянного клиента')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='main_app.staff', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.AddField(
            model_name='dishes',
            name='workpiece',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.workpieces', verbose_name='Заготовка'),
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredients', models.CharField(max_length=200, verbose_name='Ингредиенты')),
                ('number_of_positions', models.IntegerField(verbose_name='Количество позиций')),
                ('delivery_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата доставки')),
                ('supplier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.supplier', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Партия',
                'verbose_name_plural': 'Партии',
            },
        ),
    ]
