# Generated by Django 3.2.6 on 2021-11-08 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20211108_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='client',
        ),
    ]
