# Generated by Django 3.2.6 on 2021-11-29 15:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_receipt_check_closing_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='check_closing_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 29, 15, 26, 53, 845829, tzinfo=utc), verbose_name='Дата закрытия чека'),
        ),
    ]
