# Generated by Django 3.2.6 on 2021-11-25 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20211124_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='workpieces',
            name='batch',
            field=models.ManyToManyField(related_name='workpieces', to='main_app.Batch', verbose_name='Партия'),
        ),
    ]
