# Generated by Django 3.2.6 on 2021-11-25 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_workpieces_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='batch',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.batch', verbose_name='Партия'),
        ),
    ]
