# Generated by Django 3.2.6 on 2021-11-08 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_pet_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='main_app.client', verbose_name='Client'),
        ),
    ]
