# Generated by Django 3.2.6 on 2021-11-25 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_warehouse_batch'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Warehouse',
        ),
    ]
