# Generated by Django 3.2.6 on 2021-11-25 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_delete_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishes',
            name='equipment',
            field=models.TextField(default=1, max_length=500, verbose_name='Оборудрвание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='batch',
            name='ingredients',
            field=models.TextField(max_length=500, verbose_name='Ингредиенты'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='work_experience',
            field=models.IntegerField(verbose_name='Опыт работы(лет)'),
        ),
        migrations.AlterField(
            model_name='workpieces',
            name='ingredients',
            field=models.TextField(max_length=500, verbose_name='Ингредиенты'),
        ),
    ]
