# Generated by Django 3.2.6 on 2021-11-21 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_request'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pet',
            options={'verbose_name': 'Питомец', 'verbose_name_plural': 'Питомцы'},
        ),
        migrations.AddField(
            model_name='request',
            name='pet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='main_app.pet', verbose_name='Питомец'),
        ),
    ]
