# Generated by Django 3.2.6 on 2021-11-25 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20211125_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staffs', to='main_app.positions', verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='work_experience',
            field=models.FloatField(verbose_name='Опыт работы(лет)'),
        ),
    ]
