# Generated by Django 3.2.6 on 2021-11-21 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20211121_0357'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.RemoveField(
            model_name='request',
            name='email',
        ),
        migrations.AlterField(
            model_name='pet',
            name='client',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='main_app.client', verbose_name='Client'),
            preserve_default=False,
        ),
    ]
