# Generated by Django 3.2.6 on 2021-11-25 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20211125_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='ingredients',
            field=models.TextField(max_length=500, verbose_name='Состав поставки'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batchs', to='main_app.supplier', verbose_name='Поставщик'),
        ),
    ]
