# Generated by Django 3.2.6 on 2021-11-21 01:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20211121_0403'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время создания')),
                ('duration', models.IntegerField(verbose_name='Длительность, дни')),
                ('request', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='main_app.request', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
