# Generated by Django 3.2.6 on 2021-11-25 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20211125_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='number_of_positions',
            field=models.IntegerField(blank=True, verbose_name='Количество позиций'),
        ),
    ]
