# Generated by Django 3.2.6 on 2021-11-21 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Создан', 'Создан'), ('Ожидает оплаты', 'Ожидает оплаты'), ('В транспортировке (от владельца)', 'В транспортировке (от владельца)'), ('На передержке', 'На передержке'), ('В транспортировке (к владельцу)', 'В транспортировке (к владельцу)'), ('Завершен', 'Завершен'), ('Отменен', 'Отменен')], default='Создан', max_length=40, verbose_name='Статус'),
        ),
    ]
