# Generated by Django 3.2.6 on 2021-11-21 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Создан', 'Создан'), ('Ожидает подписания договора', 'Ожидает подписания договора'), ('Ожидает оплаты', 'Ожидает оплаты'), ('В транспортировке (от владельца)', 'В транспортировке (от владельца)'), ('На передержке', 'На передержке'), ('В транспортировке (к владельцу)', 'В транспортировке (к владельцу)'), ('Завершен', 'Завершен'), ('Отменен', 'Отменен')], default='Создан', max_length=40, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=200, verbose_name='Description')),
                ('price', models.IntegerField(verbose_name='Стоимость, руб.')),
                ('order', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agreement', to='main_app.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
    ]
