# Generated by Django 3.2.6 on 2021-11-25 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_alter_batch_number_of_positions'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishes',
            name='price',
            field=models.FloatField(default=1, verbose_name='Цена'),
            preserve_default=False,
        ),
    ]
