# Generated by Django 3.2.6 on 2021-11-21 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_auto_20211121_0426'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agreement',
            options={'verbose_name': 'Договор', 'verbose_name_plural': 'Договоры'},
        ),
    ]
