# Generated by Django 3.2.6 on 2021-11-29 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_receipt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receipt',
            options={'verbose_name': 'Чек', 'verbose_name_plural': 'Чеки'},
        ),
    ]
