# Generated by Django 3.2.6 on 2021-11-21 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='workers',
            field=models.ManyToManyField(blank=True, related_name='orders', to='main_app.Worker', verbose_name='Работники'),
        ),
    ]
