# Generated by Django 3.2.6 on 2021-11-29 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_alter_receipt_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishes',
            name='workpiece',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workpieces', to='main_app.workpieces', verbose_name='Заготовка'),
        ),
    ]
