# Generated by Django 3.2.6 on 2021-11-21 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_car'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'Машина', 'verbose_name_plural': 'Машины'},
        ),
        migrations.RenameField(
            model_name='car',
            old_name='model',
            new_name='mark_n_model',
        ),
    ]
