# Generated by Django 3.2.6 on 2021-11-21 01:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_auto_20211121_0443'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_start', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время начала')),
                ('timestamp_end', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время конца')),
                ('description', models.TextField(max_length=200, verbose_name='Описание')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transport_events', to='main_app.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Машина',
                'verbose_name_plural': 'Машины',
            },
        ),
    ]
