# Generated by Django 3.2.6 on 2021-11-21 01:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_transportevent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transportevent',
            options={'verbose_name': 'Событие перевозки', 'verbose_name_plural': 'События перевозки'},
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время создания')),
                ('description', models.TextField(max_length=200, verbose_name='Описание')),
                ('video', models.FileField(upload_to='report_videos', verbose_name='Видеофайл')),
                ('image', models.ImageField(upload_to='report_images', verbose_name='Изображение')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='main_app.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Отчет',
                'verbose_name_plural': 'Отчеты',
            },
        ),
    ]
